name: overcalc
description: "Overengineered calculator."
publish_to: "none"
version: "1.7.2+172"

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  auto_size_text: ^3.0.0
  url_launcher: ^6.2.6
  change_app_package_name: ^1.1.0
  flutter_secure_storage: ^9.2.4
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.7
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  showcaseview: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/IBMPlexSans-Light.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
          weight: 700
  assets:
    - .env

flutter_launcher_icons:
  android: true

  image_path: "assets/icons/icon_classic.png"

  adaptive_icon_background: "assets/icons/icon_adaptive_background.png"
  adaptive_icon_foreground: "assets/icons/icon_adaptive_foreground.png"

  monochrome:
    image_path: "assets/icons/icon_monochrome.png"
    color: "#1A1A1A"

flutter_native_splash:
  color: "#1A1A1A"
  image: assets/icons/icon_adaptive_foreground.png
